In [183]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
#from pandas_profiling import ProfileReport 
import numpy as np 

In [184]:
#!pip install pandas-profiling

In [213]:
!pip install --upgrade pandas

Requirement already up-to-date: pandas in c:\users\mrunal metkar\anaconda3\lib\site-packages (1.3.3)


In [185]:
df = pd.read_csv('Advertising.csv')

In [186]:
df.head


<bound method NDFrame.head of      Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
5             6    8.7   48.9       75.0    7.2
6             7   57.5   32.8       23.5   11.8
7             8  120.2   19.6       11.6   13.2
8             9    8.6    2.1        1.0    4.8
9            10  199.8    2.6       21.2   10.6
10           11   66.1    5.8       24.2    8.6
11           12  214.7   24.0        4.0   17.4
12           13   23.8   35.1       65.9    9.2
13           14   97.5    7.6        7.2    9.7
14           15  204.1   32.9       46.0   19.0
15           16  195.4   47.7       52.9   22.4
16           17   67.8   36.6      114.0   12.5
17           18  281.4   39.6       55.8   24.4
18           19   69.2   20.5       18.3   11.3
19        

In [187]:
df.describe

<bound method NDFrame.describe of      Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
5             6    8.7   48.9       75.0    7.2
6             7   57.5   32.8       23.5   11.8
7             8  120.2   19.6       11.6   13.2
8             9    8.6    2.1        1.0    4.8
9            10  199.8    2.6       21.2   10.6
10           11   66.1    5.8       24.2    8.6
11           12  214.7   24.0        4.0   17.4
12           13   23.8   35.1       65.9    9.2
13           14   97.5    7.6        7.2    9.7
14           15  204.1   32.9       46.0   19.0
15           16  195.4   47.7       52.9   22.4
16           17   67.8   36.6      114.0   12.5
17           18  281.4   39.6       55.8   24.4
18           19   69.2   20.5       18.3   11.3
19    

In [188]:

#ProfileReport(df)

In [189]:
#a = ProfileReport(df)

In [190]:
#a.to_widgets()

In [191]:
x =df[["TV"]]
x

ImportError: cannot import name 'is_url' from 'pandas.io.common' (C:\Users\Mrunal Metkar\Anaconda3\lib\site-packages\pandas\io\common.py)

        TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
5      8.7
6     57.5
7    120.2
8      8.6
9    199.8
10    66.1
11   214.7
12    23.8
13    97.5
14   204.1
15   195.4
16    67.8
17   281.4
18    69.2
19   147.3
20   218.4
21   237.4
22    13.2
23   228.3
24    62.3
25   262.9
26   142.9
27   240.1
28   248.8
29    70.6
..     ...
170   50.0
171  164.5
172   19.6
173  168.4
174  222.4
175  276.9
176  248.4
177  170.2
178  276.7
179  165.6
180  156.6
181  218.5
182   56.2
183  287.6
184  253.8
185  205.0
186  139.5
187  191.1
188  286.0
189   18.7
190   39.5
191   75.5
192   17.2
193  166.8
194  149.7
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [192]:
y = df.sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
5       7.2
6      11.8
7      13.2
8       4.8
9      10.6
10      8.6
11     17.4
12      9.2
13      9.7
14     19.0
15     22.4
16     12.5
17     24.4
18     11.3
19     14.6
20     18.0
21     12.5
22      5.6
23     15.5
24      9.7
25     12.0
26     15.0
27     15.9
28     18.9
29     10.5
       ... 
170     8.4
171    14.5
172     7.6
173    11.7
174    11.5
175    27.0
176    20.2
177    11.7
178    11.8
179    12.6
180    10.5
181    12.2
182     8.7
183    26.2
184    17.6
185    22.6
186    10.3
187    17.3
188    15.9
189     6.7
190    10.8
191     9.9
192     5.9
193    19.6
194    17.3
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: sales, Length: 200, dtype: float64

In [193]:
from sklearn.linear_model import LinearRegression

In [194]:
lr = LinearRegression()

In [195]:
lr.fit(x,y)

LinearRegression()

In [196]:
lr.intercept_

7.032593549127693

In [197]:
lr.coef_

array([0.04753664])

In [198]:
lr.predict([[44.5]])

array([9.14797405])

In [199]:
lr.predict([[100]])

array([11.78625759])

In [200]:
l = [3,4,5,7,8,9,0,23,450]

In [201]:
for i in l :
    print(lr.predict([[i]]))

[7.17520347]
[7.22274011]
[7.27027675]
[7.36535003]
[7.41288667]
[7.46042331]
[7.03259355]
[8.12593628]
[28.42408174]


In [202]:
pickle.dump(lr , open('lr.sav','wb'))

In [203]:
lr.score(x,y)

0.611875050850071

In [204]:
def adj_r2(x,y):
    r2 = lr.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [205]:
adj_r2(x,y)

0.6099148238341623

In [206]:
x=df[["TV",'radio']]

In [207]:
y=df.sales

In [208]:
lr1=LinearRegression()
lr1.fit(x,y)

LinearRegression()

In [209]:
lr1.intercept_

2.9210999124051362

In [210]:
lr1.coef_

array([0.04575482, 0.18799423])

In [211]:
lr1.score(x,y)

0.8971942610828956