In [2]:
import numpy as np
lst=[1,2,3]
a=np.array(lst)

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(3,)

In [6]:
l1=[1,2,3]
l2=[4,5,6]
l3=[2,4,6]
ma=np.array([l1,l2,l3])

In [7]:
ma

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [8]:
ma.shape

(3, 3)

In [9]:
ma.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [2],
       [4],
       [6]])

In [10]:
ma.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 2, 4, 6]])

In [11]:
ma

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [12]:
ma[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [13]:
ma[1,:]

array([4, 5, 6])

In [14]:
ma[1:,1:]

array([[5, 6],
       [4, 6]])

In [15]:
ma[:1,:1]

array([[1]])

In [16]:
arr=np.arange(0,10)

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr=np.arange(0,10,step=2)

In [19]:
arr

array([0, 2, 4, 6, 8])

In [31]:
a1=np.linspace(1,13) #by default linspace gives 50 elements

In [32]:
a1

array([ 1.        ,  1.24489796,  1.48979592,  1.73469388,  1.97959184,
        2.2244898 ,  2.46938776,  2.71428571,  2.95918367,  3.20408163,
        3.44897959,  3.69387755,  3.93877551,  4.18367347,  4.42857143,
        4.67346939,  4.91836735,  5.16326531,  5.40816327,  5.65306122,
        5.89795918,  6.14285714,  6.3877551 ,  6.63265306,  6.87755102,
        7.12244898,  7.36734694,  7.6122449 ,  7.85714286,  8.10204082,
        8.34693878,  8.59183673,  8.83673469,  9.08163265,  9.32653061,
        9.57142857,  9.81632653, 10.06122449, 10.30612245, 10.55102041,
       10.79591837, 11.04081633, 11.28571429, 11.53061224, 11.7755102 ,
       12.02040816, 12.26530612, 12.51020408, 12.75510204, 13.        ])

In [33]:
a2=np.linspace(1,10,5)

In [34]:
a2

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [35]:
arr1=np.array([1,2,3])

In [40]:
arr1
arr2=arr1 
arr1[1]=4
arr2

array([1, 4, 3])

In [41]:
 arr3=np.array([4,5,6])
arr2=arr3.copy()
arr3


array([4, 5, 6])

In [42]:
val=2
arr1<val

array([ True, False, False])

In [43]:
arr1[arr1<val]

array([1])

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

In [45]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
np.random.rand(3,3)  #gives uniform distribution

array([[0.25914934, 0.64044019, 0.62484601],
       [0.28633712, 0.53977399, 0.96041735],
       [0.88486706, 0.23755939, 0.85517326]])

In [47]:
np.random.randn(3,3) #gives standard normal distribution

array([[-0.16014502,  0.46012211,  0.19699924],
       [-0.41518909, -1.52656621,  0.76213723],
       [ 0.72483527,  0.64488469,  1.40453655]])

In [53]:
np.random.randint(0,10,2)

array([3, 3])