In [1]:
import numpy as np

a=np.array([[1,4,3],[1,8,1],[1,7,2]])
tra=a.T
a
tra
q=tra.dot(a)
q
m=np.linalg.inv(q)
m
r=m.dot(tra)
r
y=np.array([1,1,2])
y.shape
s=r.dot(y)
s.shape
s

array([-9.,  1.,  2.])

In [2]:
from sklearn.linear_model import LinearRegression
l=LinearRegression()
x1=np.array([[4,3],[8,1],[7,2]])
y1=np.array([[1],[1],[2]])

w=l.fit(x1,y1)

In [3]:
l.coef_

array([[1., 2.]])

In [4]:
l.intercept_

array([-9.])