In [13]:
import pandas as pd
import numpy as np

In [51]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,LassoCV,RidgeCV,LarsCV,ElasticNet,ElasticNetCV,LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
df=pd.read_csv('Admission_Prediction.csv')

In [16]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1      337.0        118.0                4.0  4.5  4.5  9.65   
1           2      324.0        107.0                4.0  4.0  4.5  8.87   
2           3        NaN        104.0                3.0  3.0  3.5  8.00   
3           4      322.0        110.0                3.0  3.5  2.5  8.67   
4           5      314.0        103.0                2.0  2.0  3.0  8.21   

   Research  Chance of Admit  
0         1             0.92  
1         1             0.76  
2         1             0.72  
3         1             0.80  
4         0             0.65

In [17]:
df.isna().sum()

Serial No.            0
GRE Score            15
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [19]:
df['GRE Score']=df['GRE Score'].fillna(df['GRE Score'].mean())
df['TOEFL Score']=df['TOEFL Score'].fillna(df['TOEFL Score'].mean())
df['University Rating']=df['University Rating'].fillna(df['University Rating'].mean())

In [20]:
df.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [21]:
df.drop(columns=['Serial No.'],inplace=True)

In [22]:
x=df.drop(columns=['Chance of Admit'])
y=df['Chance of Admit']

In [23]:
standardsc=StandardScaler()

In [24]:
scaled_data=standardsc.fit_transform(x)

In [25]:
scaled_data

array([[ 1.84274116e+00,  1.78854223e+00,  7.78905651e-01, ...,
         1.09894429e+00,  1.77680627e+00,  8.86405260e-01],
       [ 6.70814288e-01, -3.10581135e-02,  7.78905651e-01, ...,
         1.09894429e+00,  4.85859428e-01,  8.86405260e-01],
       [ 5.12433309e-15, -5.27312752e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01,  8.86405260e-01],
       ...,
       [ 1.21170361e+00,  2.11937866e+00,  1.66568791e+00, ...,
         1.63976333e+00,  1.62785086e+00,  8.86405260e-01],
       [-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [ 9.41258951e-01,  9.61451165e-01,  7.78905651e-01, ...,
         1.09894429e+00,  7.67219636e-01, -1.12815215e+00]])

In [26]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance of Admit'],
      dtype='object')

In [28]:
scaled_data_df=pd.DataFrame(scaled_data,columns=['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA',
       'Research'])

In [29]:
scaled_data_df

GRE Score  TOEFL Score  University Rating       SOP       LOR  \
0    1.842741e+00     1.788542           0.778906  1.137360  1.098944   
1    6.708143e-01    -0.031058           0.778906  0.632315  1.098944   
2    5.124333e-15    -0.527313          -0.107877 -0.377773  0.017306   
3    4.905178e-01     0.465197          -0.107877  0.127271 -1.064332   
4   -2.306679e-01    -0.692731          -0.994659 -1.387862 -0.523513   
..            ...          ...                ...       ...       ...   
495  1.392000e+00     0.134360           1.665688  1.137360  0.558125   
496  1.842741e+00     1.623124           1.665688  1.642404  1.639763   
497  1.211704e+00     2.119379           1.665688  1.137360  1.639763   
498 -4.109644e-01    -0.692731           0.778906  0.632315  1.639763   
499  9.412590e-01     0.961451           0.778906  1.137360  1.098944   

         CGPA  Research  
0    1.776806  0.886405  
1    0.485859  0.886405  
2   -0.954043  0.886405  
3    0.154847  0.886405  
4   -0.606480 -1.128152  
..        ...       ...  
495  0.734118  0.886405  
496  2.140919  0.886405  
497  1.627851  0.886405  
498 -0.242367 -1.128152  
499  0.767220 -1.128152  

[500 rows x 7 columns]

In [32]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_df=pd.DataFrame()
vif_df['VIF']=[variance_inflation_factor(scaled_data,i) for i in range(scaled_data.shape[1])]
vif_df['Columns']=x.columns


In [33]:
vif_df

VIF            Columns
0  4.153268          GRE Score
1  3.792866        TOEFL Score
2  2.508768  University Rating
3  2.775750                SOP
4  2.037308                LOR
5  4.651670               CGPA
6  1.459311           Research

In [36]:
x_train,x_test,y_train,y_test=train_test_split(scaled_data_df,y,test_size=0.10,random_state=100)

In [37]:
x_train.shape

(450, 7)

In [38]:
lin=LinearRegression()
lin.fit(x_train,y_train)

LinearRegression()

In [39]:
lin.coef_

array([ 0.01910105,  0.01654831,  0.00508326, -0.00047758,  0.01745071,
        0.07526256,  0.0127209 ])

In [40]:
lin.intercept_

0.7204110140569641

In [44]:
import pickle
pickle.dump(lin,open('admission_prediction.pickle','wb'))

In [48]:
lin.predict(standardsc.transform([[337.000000,118.0,4.0,4.5,4.5,9.65,1]]))

array([0.95280308])

In [49]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [50]:
lin.score(x_test,y_test)

0.845560194064721

In [62]:
lassocv=LassoCV(alphas=None,cv=50,max_iter=1000,normalize=True)

In [63]:
lassocv.fit(x_train,y_train)

LassoCV(cv=50, normalize=True)

In [64]:
lassocv.alpha_

2.5304685541530637e-05

In [65]:
lasso=Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=2.5304685541530637e-05)

In [66]:
lasso.score(x_test,y_test)

0.8457056329852929

In [91]:
ridgecv=RidgeCV(alphas=np.random.uniform(0,10,50),cv=10,normalize=True)

In [92]:
ridgecv.fit(x_train,y_train)

RidgeCV(alphas=array([6.28663522, 9.93131647, 1.38047382, 2.26677994, 7.18090319,
       3.7788283 , 4.30110249, 5.97002676, 5.8488898 , 0.52789516,
       8.31269933, 4.75845354, 9.02905936, 2.56394931, 2.73654591,
       9.18305288, 2.14742238, 6.0889628 , 7.3107492 , 6.23051668,
       6.99190933, 3.18160455, 2.96937604, 7.66060922, 9.86105426,
       1.8520931 , 1.26181384, 7.85555308, 5.56808486, 6.89725947,
       3.61299547, 4.96659961, 5.28521964, 2.79144545, 1.5465215 ,
       0.28527402, 5.67982736, 0.86137124, 5.82934105, 8.39001914,
       2.14267594, 5.0360424 , 6.3762549 , 4.14871213, 5.32663747,
       8.94085063, 1.88055518, 6.95217732, 5.4442952 , 7.88785366]),
        cv=10, normalize=True)

In [93]:
ridgecv.alpha_

0.28527401582527534

In [94]:
ridge=Ridge(ridgecv.alpha_)

In [95]:
ridge.fit(x_train,y_train)

Ridge(alpha=0.28527401582527534)

In [96]:
ridge.score(x_test,y_test)

0.845676621060663

In [97]:
elasticnetcv=ElasticNetCV(alphas=None,cv=10)

In [98]:
elasticnetcv.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [99]:
elasticnetcv.alpha_

0.001860632420865411

In [100]:
elasticnetcv.l1_ratio

0.5

In [101]:
elasticnet=ElasticNet(alpha=elasticnetcv.alpha_,l1_ratio=elasticnetcv.l1_ratio)
elasticnet.fit(x_train,y_train)

ElasticNet(alpha=0.001860632420865411)

In [102]:
elasticnet.score(x_test,y_test)

0.8464012025641323