In [5]:
import pandas as pd
import numpy as np 
data_train=pd.read_csv('kc_house_train_data.csv')
data_test=pd.read_csv('kc_house_test_data.csv')


In [53]:
def get_numpy_data(features, output):
    
    features_matrix=features.to_numpy()
    x0=np.ones((len(output),1))
    x_train=np.column_stack((x0,features))
    type(x_train)
    
    
    output_matrix=output.to_numpy()
    return (x_train,output_matrix)



In [87]:
def predict_outcome(feature_matrix, weights):
    #print(feature_matrix.shape)
    #print(weights.shape)
    predictions=feature_matrix.dot(weights)
    return(predictions)


In [88]:
def feature_derivate(features,errors):
    derivative=2* np.dot(features,errors)
    return derivative

In [89]:
import math
def regression_gradient_descent(feature_matrix, output, initial_weights, step_size, tolerance):
    converged = False
    weights = np.array(initial_weights)
    while not converged:
        predictions=predict_outcome(feature_matrix, weights)
        error=predictions-output
        gradient_sum_squares=0
        for i in range(len(weights)):
            derivative=feature_derivate(feature_matrix[:,i],error)
            gradient_sum_squares = (derivative * derivative) + gradient_sum_squares
            weights[i] = weights[i] - (step_size * derivative)
        gradient_magnitude = math.sqrt(gradient_sum_squares)
        if gradient_magnitude < tolerance:
            converged = True
    return(weights)


In [90]:
simple_features=data_train['sqft_living']
my_output=data_train['price']
simple_feature_matrix, output = get_numpy_data(simple_features, my_output)
initial_weights = np.array([-47000., 1.])
step_size = 7e-12
tolerance = 2.5e7

In [91]:
train_simple_weights = regression_gradient_descent(simple_feature_matrix, output,initial_weights, step_size,tolerance)

In [92]:
train_simple_weights

array([-46999.88716555,    281.91211918])

In [93]:
train_simple_weights.shape

(2,)

In [94]:
test_simple_features=data_test['sqft_living']
test_my_output=data_test['price']
test_simple_feature_matrix, test_output = get_numpy_data(test_simple_features, test_my_output)
test_simple_weights = regression_gradient_descent(test_simple_feature_matrix, test_output,initial_weights, step_size,tolerance)

In [101]:
pred_test=predict_outcome(test_simple_feature_matrix,train_simple_weights)

In [102]:
pred_test

array([356134.443255  , 784640.86440132, 435069.83662406, ...,
       663418.65315598, 604217.10812919, 240550.47439317])

In [97]:
pred_test.shape

(4229,)

In [98]:
test_simple_feature_matrix.shape

(4229, 2)

In [99]:
def get_residual_sum_of_squares(actual,predicted):
    RSS=((predicted-actual)**2).sum()
    RSS.shape
    return RSS
RSS_test_model1=get_residual_sum_of_squares(test_output,pred_test)

In [100]:
RSS_test_model1

275395691278132.8

In [131]:
model2_features = data_train[['sqft_living','sqft_living15']]
my2_output = data_train['price']
(feature_matrix2, output2) = get_numpy_data(model2_features,my2_output)
initial_weights2 = np.array([-100000., 1., 1.])
step_size2 = 4e-12
tolerance2 = 1e9

In [140]:
data_test.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0   114101516  20140528T000000  310000.0         3        1.0         1430   
1  9297300055  20150124T000000  650000.0         4        3.0         2950   
2  1202000200  20141103T000000  233000.0         3        2.0         1710   
3  8562750320  20141110T000000  580500.0         3        2.5         2320   
4  7589200193  20141110T000000  535000.0         3        1.0         1090   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0     19901     1.5           0     0  ...      7        1430              0   
1      5000     2.0           0     3  ...      9        1980            970   
2      4697     1.5           0     0  ...      6        1710              0   
3      3980     2.0           0     0  ...      8        2320              0   
4      3000     1.5           0     0  ...      8        1090              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1927             0    98028  47.7558 -122.229           1780   
1      1979             0    98126  47.5714 -122.375           2140   
2      1941             0    98002  47.3048 -122.218           1030   
3      2003             0    98027  47.5391 -122.070           2580   
4      1929             0    98117  47.6889 -122.375           1570   

   sqft_lot15  
0       12697  
1        4000  
2        4705  
3        3980  
4        5080  

[5 rows x 21 columns]

In [133]:
feature_matrix2

array([[1.00e+00, 1.18e+03, 1.34e+03],
       [1.00e+00, 2.57e+03, 1.69e+03],
       [1.00e+00, 7.70e+02, 2.72e+03],
       ...,
       [1.00e+00, 1.53e+03, 1.53e+03],
       [1.00e+00, 1.60e+03, 1.41e+03],
       [1.00e+00, 1.02e+03, 1.02e+03]])

In [134]:
train_simple_weights_model2 = regression_gradient_descent(feature_matrix2, output2,initial_weights2, step_size2,tolerance2)

In [135]:
test_simple_features2=data_test[['sqft_living','sqft_living15']]
test_my_output2=data_test['price']
test_simple_feature_matrix2, test_output2 = get_numpy_data(test_simple_features2, test_my_output2)
pred_test2=predict_outcome(test_simple_feature_matrix2,train_simple_weights_model2)

In [136]:
RSS_test_model2=get_residual_sum_of_squares(test_my_output2,pred_test2)

In [137]:
RSS_test_model2

270263443629803.56

In [138]:
pred_test2

array([366651.41162949, 762662.39850726, 386312.09557541, ...,
       682087.39916306, 585579.27901327, 216559.20391786])

In [139]:
train_simple_weights_model2

array([-9.99999688e+04,  2.45072603e+02,  6.52795267e+01])